/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GiaoDien;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author hongd
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        init();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/logoBonBon.png"));
        setIconImage(icon.getImage());
    }

    void init() {
        setLocationRelativeTo(null);

        new LoadForm(this, true).setVisible(true);
        DangNhap dn = new DangNhap(this, true);
        dn.setVisible(true);

        if (!dn.isDangNhapThanhCong()) {
            System.exit(0); // Thoát chương trình nếu người dùng không đăng nhập
        }
        this.startDongHo();
    }

    void startDongHo() {
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
        new Timer(1000, (ActionEvent e) -> {
            DongHo.setText(formater.format(new Date()));
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnNhanVien = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnDonHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnHDCT = new javax.swing.JButton();
        btnTongHopThongKe = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnGioiThieu = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        TabGDC = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        DongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniQLNV = new javax.swing.JMenuItem();
        mniQLSP = new javax.swing.JMenuItem();
        mniKho = new javax.swing.JMenuItem();
        mniQLKH = new javax.swing.JMenuItem();
        mniQLDH = new javax.swing.JMenuItem();
        mniQLHD = new javax.swing.JMenuItem();
        mniHDCT = new javax.swing.JMenuItem();
        jmenu = new javax.swing.JMenu();
        mniThongKe = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniGioiThieu = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUÁN BONBONCOFFEE");

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        btnNhanVien.setText(" Nhân viên ");
        btnNhanVien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNhanVien);

        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Color wheel.png"))); // NOI18N
        btnSanPham.setText(" Sản phẩm ");
        btnSanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSanPham);

        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boy.png"))); // NOI18N
        btnKhachHang.setText(" Khách hàng ");
        btnKhachHang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKhachHang);

        btnKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Safe.png"))); // NOI18N
        btnKho.setText("     Kho     ");
        btnKho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKho.setFocusable(false);
        btnKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKho);

        btnDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add to basket.png"))); // NOI18N
        btnDonHang.setText(" Đơn hàng ");
        btnDonHang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDonHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDonHang);

        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dollar.png"))); // NOI18N
        btnHoaDon.setText(" Hóa đơn ");
        btnHoaDon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHoaDon);

        btnHDCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Price list.png"))); // NOI18N
        btnHDCT.setText(" Hóa đơn chi tiết ");
        btnHDCT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHDCT.setFocusable(false);
        btnHDCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHDCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHDCT);

        btnTongHopThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bar chart.png"))); // NOI18N
        btnTongHopThongKe.setText(" Tổng hợp-Thống kê ");
        btnTongHopThongKe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTongHopThongKe.setFocusable(false);
        btnTongHopThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTongHopThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTongHopThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongHopThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTongHopThongKe);

        jSeparator2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.add(jSeparator2);

        btnGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Info.png"))); // NOI18N
        btnGioiThieu.setText(" Giới thiệu ");
        btnGioiThieu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGioiThieu.setFocusable(false);
        btnGioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGioiThieu);

        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnDoiMatKhau.setText(" Đổi mật khẩu ");
        btnDoiMatKhau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDoiMatKhau);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        DongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Alarm.png"))); // NOI18N
        DongHo.setText("00:00 AM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(984, Short.MAX_VALUE)
                .addComponent(DongHo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DongHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gear.png"))); // NOI18N

        mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mniDoiMatKhau);

        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniDangXuat);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Address book.png"))); // NOI18N

        mniQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        mniQLNV.setText("Quản lý nhân viên");
        mniQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNVActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLNV);

        mniQLSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Color wheel.png"))); // NOI18N
        mniQLSP.setText("Quản lý sản phẩm");
        mniQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLSPActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLSP);

        mniKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Safe.png"))); // NOI18N
        mniKho.setText("Kho");
        mniKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoActionPerformed(evt);
            }
        });
        jMenu2.add(mniKho);

        mniQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boy.png"))); // NOI18N
        mniQLKH.setText("Quản lý khách hàng");
        mniQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLKHActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLKH);

        mniQLDH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add to basket.png"))); // NOI18N
        mniQLDH.setText("Quản lý đơn hàng");
        mniQLDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLDHActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLDH);

        mniQLHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dollar.png"))); // NOI18N
        mniQLHD.setText("Quản lý hóa đơn");
        mniQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLHDActionPerformed(evt);
            }
        });
        jMenu2.add(mniQLHD);

        mniHDCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Price list.png"))); // NOI18N
        mniHDCT.setText("Quản lý HĐ chi tiết");
        mniHDCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHDCTActionPerformed(evt);
            }
        });
        jMenu2.add(mniHDCT);

        jMenuBar1.add(jMenu2);

        jmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Best.png"))); // NOI18N

        mniThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bar chart.png"))); // NOI18N
        mniThongKe.setText("Tổng hợp-Thống kê");
        mniThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeActionPerformed(evt);
            }
        });
        jmenu.add(mniThongKe);

        jMenuBar1.add(jmenu);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Info.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        jMenu4.add(mniGioiThieu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabGDC, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabGDC, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGioiThieuActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Giới thiệu")) {
                TabGDC.setSelectedIndex(i); // Chuyển ngay đến tab đã có
                return;
            }
        }

        GioiThieu gt = new GioiThieu();
        JPanel panel = new JPanel();
        panel.add(gt.getContentPane());
        TabGDC.addTab("Giới thiệu", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Giới thiệu");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Giới thiệu", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnGioiThieuActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Sản phẩm")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLySanPham qlsp = new QuanLySanPham();
        JPanel panel = new JPanel();
        panel.add(qlsp.getContentPane());
        TabGDC.addTab("Sản phẩm", panel);

        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Sản phẩm");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Sản phẩm", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Nhân viên")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        JPanel panel = new JPanel();
        panel.add(qlnv.getContentPane());
        TabGDC.addTab("Nhân viên", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Nhân viên");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Nhân viên", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Khách hàng")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyKhachHang qlkh = new QuanLyKhachHang();
        JPanel panel = new JPanel();
        panel.add(qlkh.getContentPane());
        TabGDC.addTab("Khách hàng", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Khách hàng");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Khách hàng", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonHangActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Đơn hàng")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyDonHang qldh = new QuanLyDonHang();
        JPanel panel = new JPanel();
        panel.add(qldh.getContentPane());
        TabGDC.addTab("Đơn hàng", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Đơn hàng");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Đơn hàng", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnDonHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Hóa đơn")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyHoaDon qlhd = new QuanLyHoaDon();
        JPanel panel = new JPanel();
        panel.add(qlhd.getContentPane());
        TabGDC.addTab("Hóa đơn", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Hóa đơn");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Hóa đơn", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnTongHopThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongHopThongKeActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Tổng hợp - thống kê")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        ThongKe tk = new ThongKe();
        JPanel panel = new JPanel();
        panel.add(tk.getContentPane());
        TabGDC.addTab("Tổng hợp - thống kê", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Tổng hợp - thống kê");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Tổng hợp - thống kê", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnTongHopThongKeActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau dmk = new DoiMatKhau();
        dmk.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau dmk = new DoiMatKhau();
        dmk.setVisible(true);
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất ?", "Đăng xuất", JOptionPane.YES_NO_CANCEL_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            DangNhap dn = new DangNhap(this, rootPaneCheckingEnabled);
            dn.setVisible(true);
        }
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLKHActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Khách hàng")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyKhachHang qlkh = new QuanLyKhachHang();
        JPanel panel = new JPanel();
        panel.add(qlkh.getContentPane());
        TabGDC.addTab("Khách hàng", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Khách hàng");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Khách hàng", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniQLKHActionPerformed

    private void mniQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNVActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Nhân viên")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyNhanVien qlnv = new QuanLyNhanVien();
        JPanel panel = new JPanel();
        panel.add(qlnv.getContentPane());
        TabGDC.addTab("Nhân viên", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Nhân viên");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Nhân viên", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniQLNVActionPerformed

    private void mniQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLSPActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Sản phẩm")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLySanPham qlsp = new QuanLySanPham();
        JPanel panel = new JPanel();
        panel.add(qlsp.getContentPane());
        TabGDC.addTab("Sản phẩm", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Sản phẩm");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Sản phẩm", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniQLSPActionPerformed

    private void mniQLDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLDHActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Đơn hàng")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyDonHang qldh = new QuanLyDonHang();
        JPanel panel = new JPanel();
        panel.add(qldh.getContentPane());
        TabGDC.addTab("Đơn hàng", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Đơn hàng");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Đơn hàng", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniQLDHActionPerformed

    private void mniQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLHDActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Hóa đơn")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyHoaDon qlhd = new QuanLyHoaDon();
        JPanel panel = new JPanel();
        panel.add(qlhd.getContentPane());
        TabGDC.addTab("Hóa đơn", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Hóa đơn");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Hóa đơn", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniQLHDActionPerformed

    private void mniThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Tổng hợp - thống kê")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        ThongKe tk = new ThongKe();
        JPanel panel = new JPanel();
        panel.add(tk.getContentPane());
        TabGDC.addTab("Tổng hợp - thống kê", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Tổng hợp - thống kê");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Tổng hợp - thống kê", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniThongKeActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Giới thiệu")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        GioiThieu gt = new GioiThieu();
        JPanel panel = new JPanel();
        panel.add(gt.getContentPane());
        TabGDC.addTab("Giới thiệu", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Giới thiệu");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Giới thiệu", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDCTActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Hóa đơn chi tiết")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyHDCT qlhdct = new QuanLyHDCT();
        JPanel panel = new JPanel();
        panel.add(qlhdct.getContentPane());
        TabGDC.addTab("Hóa đơn chi tiết", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Hóa đơn chi tiết");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Hóa đơn chi tiết", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnHDCTActionPerformed

    private void mniHDCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHDCTActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Hóa đơn chi tiết")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyHDCT qlhdct = new QuanLyHDCT();
        JPanel panel = new JPanel();
        panel.add(qlhdct.getContentPane());
        TabGDC.addTab("Hóa đơn chi tiết", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Hóa đơn chi tiết");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Hóa đơn chi tiết", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniHDCTActionPerformed

    private void mniKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Kho")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyKho k = new QuanLyKho();
        JPanel panel = new JPanel();
        panel.add(k.getContentPane());
        TabGDC.addTab("Kho", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Kho");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Kho", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_mniKhoActionPerformed

    private void btnKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < TabGDC.getTabCount(); i++) {
            if (TabGDC.getTitleAt(i).equals("Kho")) {
                TabGDC.setSelectedIndex(i);
                return;
            }
        }
        QuanLyKho k = new QuanLyKho();
        JPanel panel = new JPanel();
        panel.add(k.getContentPane());
        TabGDC.addTab("Kho", panel);
        
        JPanel tabHeader = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        JLabel titleLabel = new JLabel("Kho");
        JButton closeButton = new JButton("x");

        closeButton.setMargin(new Insets(0, 2, 0, 2));
        closeButton.setFont(new Font("Arial", Font.BOLD, 12));
        closeButton.setBorder(BorderFactory.createEmptyBorder());
        closeButton.setFocusPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setOpaque(false);

        closeButton.addActionListener(e -> {
            int index = TabGDC.indexOfComponent(panel);
            if (index != -1) {
                TabGDC.remove(index);
            }
        });

        tabHeader.add(titleLabel);
        tabHeader.add(closeButton);

        TabGDC.addTab("Kho", panel);
        int index = TabGDC.indexOfComponent(panel);
        TabGDC.setTabComponentAt(index, tabHeader);
        TabGDC.setSelectedIndex(index);
    }//GEN-LAST:event_btnKhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DongHo;
    private javax.swing.JTabbedPane TabGDC;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnDonHang;
    private javax.swing.JButton btnGioiThieu;
    private javax.swing.JButton btnHDCT;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTongHopThongKe;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmenu;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHDCT;
    private javax.swing.JMenuItem mniKho;
    private javax.swing.JMenuItem mniQLDH;
    private javax.swing.JMenuItem mniQLHD;
    private javax.swing.JMenuItem mniQLKH;
    private javax.swing.JMenuItem mniQLNV;
    private javax.swing.JMenuItem mniQLSP;
    private javax.swing.JMenuItem mniThongKe;
    // End of variables declaration//GEN-END:variables
}
